Rename material design icon, fix documentation URL
sehaas/ha_hisense_tv pull request #5
Opened 2021-10-16 02:13 UTC by lindsaymarkward

Thanks for this project!
I got log errors like:
```2021-10-15 07:37:21 WARNING (MainThread) [frontend.js.latest.202110071] Icon mdi:television-clean was renamed to mdi:television-shimmer, please change your config, it will be removed in version 2021.12. ```

So, I have renamed the icon.
I also got a 404 when trying to access the docs from HACS, so I have corrected this as well.

I am participating in #hacktoberfest, so I would appreciate if you could add the 'hacktoberfest-accepted' label.

Thanks 👍

2021-10-16 07:13 UTC, sehaas requested changes

2021-10-16 07:13 UTC, sehaas commented on custom_components/hisense_tv/manifest.json
> +    "version": "21.4.9",
You could not know, but the version number was intended to reflect the release date (YY-M-D). So use something around `21.10.16`

2021-10-16 07:13 UTC, sehaas commented on custom_components/hisense_tv/helper.py
> +        self._icon = "mdi:television-shimmer"
`mdi:television-shimmer` is only available from `2021.10.0` onwards. I'm not sure how to support previous HA versions as well. Not everyone is updating right away (if there isn't a security problem).

2021-10-16 09:20 UTC, lindsaymarkward commented on custom_components/hisense_tv/helper.py
> +        self._icon = "mdi:television-shimmer"
I'm not really sure how it works, but I believe this would be a breaking change (at least in terms of the icon) for people with HA < 2021.10. I think that's probably acceptable since users don't get automatically upgraded.

2021-10-16 09:20 UTC, lindsaymarkward commented on custom_components/hisense_tv/manifest.json
> +    "version": "21.4.9",
I've updated this now; will request re-review.

2021-10-16 09:23 UTC, lindsaymarkward commented
For Hacktoberfest, I believe you as the repo owner can either:

- add the 'hacktoberfest 'topic to the repo, or 
- label the PR as 'hacktoberfest-accepted'

https://hacktoberfest.digitalocean.com/faq

Thanks.

2021-10-16 12:42 UTC, sehaas commented on custom_components/hisense_tv/helper.py
> +        self._icon = "mdi:television-shimmer"
you could set the icon depending on `__short_version__` from [homeassitant.const](https://github.com/home-assistant/core/blob/71e2fb62afba3d142fd18bc11216cd08c005e907/homeassistant/const.py#L9)

2021-11-05 07:09 UTC, lindsaymarkward commented
Hi @sehaas - would you consider this PR again now that HA 2021.11 is out? 
The renamed icon won't be available in the next version (.12). I just saw the message in my logs. Thanks.

2021-11-05 07:24 UTC, sehaas commented
Yes I haven't forgotten this PR, but there was no reaction to my suggestion.
Could you change the code to keep it backwards compatible by checking the version number?

2021-11-23 21:32 UTC, sehaas commented
Thanks for the initial PR. I added your commit and extended the version check.

2021-11-23 21:32 UTC, closed without merging

2021-11-25 00:17 UTC, lindsaymarkward commented
Great! Glad I could help even just a tiny bit.